CFLAGS = -g -Wall -std=c++14
LIBS =  -lpthread

SRCS = Thread_test2.cpp
EXECUTABLE = ThreadTest2
CC = g++

all:
	$(CC) $(CFLAGS) -o $(EXECUTABLE) $(SRCS) $(LIBS)

.PHONY:clean
clean:
	rm $(EXECUTABLE)

